name: decode_brain
channels:
  - defaults
dependencies:
  - scikit-image
  - scikit-learn
  - pandas
  - python=3.9
  - numpy
  - pip
  - scipy
  - openpyxl
  - torchvision
  - pytorch
  - h5py
  - pip:
    - notebook
    - matplotlib
    - mne-bids
    - torchviz
    - nilearn
    - nimare
    - allensdk
    - threadpoolctl==3.1.0
    - quarto